# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: topo.onosproject.org/v1beta1
kind: Entity
metadata:
  name: {{.Name}}
spec:
  uri: {{.EntityID}} # protocol:switchID/port_number/channel_number
  kind:
    name: port
  aspects:
    onos.topo.PhyPort:
      port_number: {{.PortNumber}}
      display_name: "{{.DisplayName}}"
      speed: {{.Speed}}
      channel_number: {{.ChannelNumber}}
---

