# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: topo.onosproject.org/v1beta1
kind: Entity
metadata:
  name: {{.Name}}
spec:
  uri: {{.EntityID}} # protocol:switch_id
  kind:
    name: switch
  aspects:
    onos.topo.Switch:
      model_id: "{{.ModelID}}"
      role: "{{.Role}}"
    onos.topo.P4RTServerInfo:
      control_endpoint:
        address: {{.P4RTAddress}}
        port: {{.P4RTPort}}
      device_id: 1
    onos.topo.TLSOptions:
      plain: true
      insecure: {{.Insecure}}
---

