// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/northbound/proto/admin.proto

// Package admin defines the administrative and diagnostic gRPC interfaces.

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("pkg/northbound/proto/admin.proto", fileDescriptor_a91573d9ad3811b0) }

var fileDescriptor_a91573d9ad3811b0 = []byte{
	// 81 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0xc8, 0x4e, 0xd7,
	0xcf, 0xcb, 0x2f, 0x2a, 0xc9, 0x48, 0xca, 0x2f, 0xcd, 0x4b, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9,
	0xd7, 0x4f, 0x4c, 0xc9, 0xcd, 0xcc, 0xd3, 0x03, 0xb3, 0x85, 0x58, 0xc1, 0x94, 0x91, 0x10, 0x97,
	0x40, 0x48, 0x7e, 0x41, 0xbe, 0x23, 0x48, 0x26, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x35, 0x89,
	0x0d, 0x2c, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x4d, 0xc2, 0xff, 0x45, 0x00, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TopoAdminServiceClient is the client API for TopoAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TopoAdminServiceClient interface {
}

type topoAdminServiceClient struct {
	cc *grpc.ClientConn
}

func NewTopoAdminServiceClient(cc *grpc.ClientConn) TopoAdminServiceClient {
	return &topoAdminServiceClient{cc}
}

// TopoAdminServiceServer is the server API for TopoAdminService service.
type TopoAdminServiceServer interface {
}

// UnimplementedTopoAdminServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTopoAdminServiceServer struct {
}

func RegisterTopoAdminServiceServer(s *grpc.Server, srv TopoAdminServiceServer) {
	s.RegisterService(&_TopoAdminService_serviceDesc, srv)
}

var _TopoAdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TopoAdminService",
	HandlerType: (*TopoAdminServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "pkg/northbound/proto/admin.proto",
}
