# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: topo.onosproject.org/v1beta1
kind: Entity
metadata:
  name: network-layer.0.underlay-1
spec:
  uri: network-layer:0/underlay-1 # network-layer:type/name
  kind:
    name: network-layer
  aspects:
    onos.topo.NetworkLayer:
      type: "UNDERLAY"
      display_name: "underlay-1"
---

# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: topo.onosproject.org/v1beta1
kind: Entity
metadata:
  name: p4rt.1
spec:
  uri: p4rt:1 # protocol:switch_id
  kind:
    name: switch
  aspects:
    onos.topo.Switch:
      model_id: "test"
      role: "leaf"
    onos.topo.P4RTServerInfo:
      control_endpoint:
        address: stratum-simulator
        port: 50002
    onos.topo.TLSOptions:
      plain: true
      insecure: true
---

# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: topo.onosproject.org/v1beta1
kind: Entity
metadata:
  name: network-layer.0.underlay-2
spec:
  uri: network-layer:0/underlay-2 # network-layer:type/name
  kind:
    name: network-layer
  aspects:
    onos.topo.NetworkLayer:
      type: "UNDERLAY"
      display_name: "underlay-2"
---

# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: topo.onosproject.org/v1beta1
kind: Entity
metadata:
  name: network-layer.0.underlay-1
spec:
  uri: network-layer:0/underlay-1 # network-layer:type/name
  kind:
    name: network-layer
  aspects:
    onos.topo.NetworkLayer:
      type: "UNDERLAY"
      display_name: "underlay-1"
---

# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: topo.onosproject.org/v1beta1
kind: Entity
metadata:
  name: p4rt.1
spec:
  uri: p4rt:1 # protocol:switch_id
  kind:
    name: switch
  aspects:
    onos.topo.Switch:
      model_id: "test"
      role: "leaf"
    onos.topo.P4RTServerInfo:
      control_endpoint:
        address: stratum-simulator
        port: 50002
    onos.topo.TLSOptions:
      plain: true
      insecure: true
---

# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: topo.onosproject.org/v1beta1
kind: Entity
metadata:
  name: network-layer.0.underlay-2
spec:
  uri: network-layer:0/underlay-2 # network-layer:type/name
  kind:
    name: network-layer
  aspects:
    onos.topo.NetworkLayer:
      type: "UNDERLAY"
      display_name: "underlay-2"
---

# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: topo.onosproject.org/v1beta1
kind: Entity
metadata:
  name: network-layer.0.underlay-1
spec:
  uri: network-layer:0/underlay-1 # network-layer:type/name
  kind:
    name: network-layer
  aspects:
    onos.topo.NetworkLayer:
      type: "UNDERLAY"
      display_name: "underlay-1"
---

# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: topo.onosproject.org/v1beta1
kind: Entity
metadata:
  name: p4rt.1
spec:
  uri: p4rt:1 # protocol:switch_id
  kind:
    name: switch
  aspects:
    onos.topo.Switch:
      model_id: "test"
      role: "leaf"
    onos.topo.P4RTServerInfo:
      control_endpoint:
        address: stratum-simulator
        port: 50002
    onos.topo.TLSOptions:
      plain: true
      insecure: true
---

# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: topo.onosproject.org/v1beta1
kind: Entity
metadata:
  name: network-layer.0.underlay-2
spec:
  uri: network-layer:0/underlay-2 # network-layer:type/name
  kind:
    name: network-layer
  aspects:
    onos.topo.NetworkLayer:
      type: "UNDERLAY"
      display_name: "underlay-2"
---

